countries = ['USA', 'Australia', 'Senegal', 'Brazil', 'Wales']
print(countries)
print (sorted (countries))
print(countries)
print(sorted(countries, reverse=True))
print(countries)
print(countries.reverse)
countries.reverse()
print(countries)
countries.reverse()
print(countries)
countries.sort()
print (countries)
countries.sort(reverse=True)
print (countries)